package guru.urchin.scan

/**
 * Protocol-agnostic union DTO carrying fields from all supported protocols.
 * Built by per-protocol observation builders and consumed by [ObservationRecorder]
 * to write into the Room database.
 *
 * Field groups: core identity (name, address, rssi, timestamp), legacy BLE
 * fields (serviceUuids through classificationEvidence), protocol type,
 * TPMS (tpmsModel–tpmsSnr), POCSAG (pocsagCapCode–pocsagMessage),
 * ADS-B (adsbIcao–adsbSquawk), P25 (p25UnitId–p25TalkGroupId).
 */
data class ObservationInput(
  val name: String?,
  val address: String?,
  val rssi: Int,
  val timestamp: Long,
  val serviceUuids: List<String>,
  val manufacturerData: Map<Int, String>,
  val serviceData: Map<String, String> = emptyMap(),
  val source: String,
  val transport: String? = null,
  val advertisedName: String? = null,
  val systemName: String? = null,
  val nameSource: String? = null,
  val vendorName: String? = null,
  val vendorSource: String? = null,
  val vendorConfidence: String? = null,
  val locallyAdministeredAddress: Boolean? = null,
  val normalizedAddress: String? = null,
  val addressType: String? = null,
  val addressTypeLabel: String? = null,
  val rawAndroidAddressType: Int? = null,
  val deviceType: Int? = null,
  val deviceTypeLabel: String? = null,
  val bondState: Int? = null,
  val bondStateLabel: String? = null,
  val advertiseFlags: Int? = null,
  val txPowerLevel: Int? = null,
  val resultTxPower: Int? = null,
  val connectable: Boolean? = null,
  val legacy: Boolean? = null,
  val dataStatus: Int? = null,
  val primaryPhy: Int? = null,
  val secondaryPhy: Int? = null,
  val advertisingSid: Int? = null,
  val periodicAdvertisingInterval: Int? = null,
  val appearance: Int? = null,
  val appearanceLabel: String? = null,
  val classicMajorClass: Int? = null,
  val classicMajorClassLabel: String? = null,
  val classicDeviceClass: Int? = null,
  val classicDeviceClassLabel: String? = null,
  val passiveDecoderHints: List<String> = emptyList(),
  val classificationFingerprint: String? = null,
  val classificationCategory: String? = null,
  val classificationLabel: String? = null,
  val classificationConfidence: String? = null,
  val classificationEvidence: List<String> = emptyList(),
  val protocolType: String? = null,
  val tpmsModel: String? = null,
  val tpmsSensorId: String? = null,
  val tpmsPressureKpa: Double? = null,
  val tpmsTemperatureC: Double? = null,
  val tpmsBatteryOk: Boolean? = null,
  val tpmsFrequencyMhz: Double? = null,
  val tpmsSnr: Double? = null,
  val pocsagCapCode: String? = null,
  val pocsagFunctionCode: Int? = null,
  val pocsagMessage: String? = null,
  val adsbIcao: String? = null,
  val adsbCallsign: String? = null,
  val adsbAltitude: Int? = null,
  val adsbSpeed: Double? = null,
  val adsbHeading: Double? = null,
  val adsbLat: Double? = null,
  val adsbLon: Double? = null,
  val adsbSquawk: String? = null,
  val p25UnitId: String? = null,
  val p25Nac: String? = null,
  val p25Wacn: String? = null,
  val p25SystemId: String? = null,
  val p25TalkGroupId: String? = null,
  val rawJson: String? = null
)
